-- HLS streaming (Phase 11).
ALTER TABLE stations ADD COLUMN hls_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE stations ADD COLUMN hls_dir TEXT NOT NULL DEFAULT '';
ALTER TABLE stations ADD COLUMN hls_segment_seconds DOUBLE PRECISION NOT NULL DEFAULT 5.0;
ALTER TABLE stations ADD COLUMN hls_retention BIGINT NOT NULL DEFAULT 12;
