//! Station model → `crabsoup.lua` generator.
//!
//! The generated script mirrors the engine's example script
//! (`../crabsoup/crabsoup.lua.example`): the PCM bus is pinned with `set()`,
//! sources (playlists, jingles, harbor) are wired into a `fallback`, and the
//! result is broadcast via `output.icecast`. Every generated script must
//! pass `crabsoup --check` before the supervisor applies it (see
//! [`validate`]).
//!
//! When the station has DB playlists, the `pl` source is composed from them
//! (per-playlist `playlist({files = ...})` with `annotate:` fade/cue
//! overrides, dayparted `switch` for `scheduled` playlists, `rotate` with
//! weights across concurrent playlists). With no playlists, the legacy
//! `playlist({directory = ...})` line is emitted unchanged.

use std::fmt::Write;
use std::path::Path;
use std::process::Command;

use crate::db::playlists::PlaylistSource;
use crate::db::stations::Station;

/// Render the station's `crabsoup.lua`.
///
/// No secrets: the harbor/icecast passwords come from the station config,
/// not from env, so a rendered script is self-contained — but `--check`
/// runs against the file, and the file lives under the station's config
/// dir, not in the repo.
///
/// `webhook_url` is the backend's track webhook and `blank_webhook_url`
/// the dead-air webhook (the engine's `http_post` carries no headers, so
/// the station id rides in the query string). The output chain is wrapped
/// in `blank.detect` (see the generated script below) so dead air raises an
/// alert through the blank webhook.
pub fn render(
    station: &Station,
    webhook_url: &str,
    blank_webhook_url: &str,
    playlists: &[PlaylistSource],
    streamer_passwords: &[String],
) -> String {
    let mut s = String::new();
    let _ = writeln!(
        s,
        "-- Generated by crabcast for station {:?}. Do not edit; the server regenerates this.",
        station.id
    );
    let _ = writeln!(s);
    let _ = writeln!(s, "set(\"sample_rate\", {})", station.sample_rate);
    let _ = writeln!(s, "set(\"channels\", {})", station.channels);
    let _ = writeln!(
        s,
        "set(\"frames_per_buffer\", {})",
        station.frames_per_buffer
    );
    let _ = writeln!(s);
    let _ = writeln!(
        s,
        "set(\"crossfade_seconds\", {})",
        fmt_f64(station.crossfade_seconds)
    );
    let _ = writeln!(s, "set(\"fade_curve\", {})", fmt_f64(station.fade_curve));
    let _ = writeln!(
        s,
        "set(\"duck_seconds\", {})",
        fmt_f64(station.duck_seconds)
    );
    let _ = writeln!(s);
    render_playlist_sources(&mut s, playlists, &station.playlist_dir);
    let _ = writeln!(s);
    if station.jingles_dir.is_empty() {
        // The engine's jingles() rejects an empty set at `--check` time, so a
        // station without a jingles dir simply leaves the jingle source out.
        let _ = writeln!(s, "-- no jingles configured");
    } else {
        let _ = writeln!(s, "j = jingles({{directory = {:?}}})", station.jingles_dir);
    }
    let _ = writeln!(s);
    // Per-streamer source passwords ride as extra valid harbor passwords
    // (the engine accepts any of them); the station password stays the
    // shared/default one.
    let extra = if streamer_passwords.is_empty() {
        String::new()
    } else {
        let quoted: Vec<String> = streamer_passwords
            .iter()
            .map(|p| format!("{p:?}"))
            .collect();
        format!(", extra_passwords = {{{}}}", quoted.join(", "))
    };
    let _ = writeln!(
        s,
        "live = input.harbor({{host = \"0.0.0.0\", port = {}, mount = {:?}, password = {:?}{extra}}})",
        station.harbor_port, station.harbor_mount, station.harbor_password
    );
    let _ = writeln!(s);
    let _ = writeln!(
        s,
        "server.telnet({{host = \"127.0.0.1\", port = {}, http_port = {}, banner = false}})",
        station.control_port, station.control_http_port
    );
    let _ = writeln!(s);
    let _ = writeln!(s, "rq = request.queue()");
    let _ = writeln!(s);
    // Dead-air guard: after 5s of silence the wrapped chain goes blank
    // (still emitting silence — `exhaust_while_blank = false` keeps the
    // Icecast mount alive) and the `on_blank` hook pings the backend,
    // which raises a `dead_air` alert. It recovers on its own when audio
    // returns.
    let chain = if station.jingles_dir.is_empty() {
        "{live, rq, pl}"
    } else {
        "{j, live, rq, pl}"
    };
    let _ = writeln!(
        s,
        "air = blank.detect(fallback({chain}), {{threshold = -40, duration = 5, exhaust_while_blank = false, on_blank = function() http_post({:?}, {{}}) end}})",
        format!("{blank_webhook_url}?station={}", station.id),
    );
    let _ = writeln!(s);
    let _ = writeln!(
        s,
        "output.icecast({{host = {:?}, port = {}, mount = {:?}, format = {:?}, bitrate = {}, source_user = {:?}, source_password = {:?}, name = {:?}, description = {:?}, genre = \"Various\", reconnect = 5}}, on_metadata(air, function(m) http_post({:?}, m) end))",
        station.icecast_host,
        station.icecast_port,
        station.icecast_mount,
        station.icecast_format,
        station.icecast_bitrate,
        station.icecast_source_user,
        station.icecast_source_password,
        station.name,
        station.description,
        format!("{webhook_url}?station={}", station.id),
    );
    let _ = writeln!(s);
    s
}

/// Emit the `pl` source: either the legacy directory playlist (no DB
/// playlists) or a composition of the station's playlists:
///
/// - each enabled playlist becomes `pl{i} = playlist({files = {...}, shuffle, loop})`;
/// - per-track overrides are baked in as `annotate:` prefixes;
/// - `scheduled` playlists are wrapped in a `switch` using their schedule
///   rules (day names + HH:MM windows), with the fallback child being the
///   other playlists (or the legacy directory playlist when no DB playlist
///   is enabled — a scheduled-only station still needs an on-air default);
/// - multiple always-on playlists are combined with `rotate` + weights;
/// - `once_per_hour` playlists are joined with `rotate` weights too (the
///   engine has no per-hour primitive; the schedule window approximates it).
pub fn render_playlist_sources(s: &mut String, playlists: &[PlaylistSource], fallback_dir: &str) {
    let enabled: Vec<&PlaylistSource> = playlists.iter().filter(|p| !p.files.is_empty()).collect();

    if enabled.is_empty() {
        let _ = writeln!(
            s,
            "pl = playlist({{directory = {:?}, shuffle = false, loop = true}})",
            fallback_dir
        );
        return;
    }

    // One playlist() source per DB playlist.
    for (i, p) in enabled.iter().enumerate() {
        let shuffle = if p.kind == "looping" {
            "false"
        } else if p.shuffle {
            "true"
        } else {
            "false"
        };
        let files: Vec<String> = p
            .files
            .iter()
            .map(|(path, fade_in, fade_out, cue_in, cue_out)| {
                annotate_path(path, *fade_in, *fade_out, *cue_in, *cue_out)
            })
            .collect();
        let _ = writeln!(
            s,
            "pl{i} = playlist({{files = {{{}}}, shuffle = {shuffle}, loop = true}})",
            files.join(", ")
        );
    }

    // Always-on children: standard/looping playlists, plus once_per_hour
    // (they rotate like any other; a per-hour schedule is approximated by
    // the `scheduled` switch below, see comments).
    let always: Vec<usize> = enabled
        .iter()
        .enumerate()
        .filter(|(_, p)| p.kind != "scheduled")
        .map(|(i, _)| i)
        .collect();

    let scheduled: Vec<usize> = enabled
        .iter()
        .enumerate()
        .filter(|(_, p)| p.kind == "scheduled")
        .map(|(i, _)| i)
        .collect();

    // Build the base (non-scheduled) composition: rotate with weights when
    // more than one playlist, otherwise the single source.
    let base = match always.len() {
        0 => "mksafe(blank())".to_string(),
        1 => format!("pl{}", always[0]),
        _ => {
            let names: Vec<String> = always.iter().map(|i| format!("pl{i}")).collect();
            let weights: Vec<String> = always
                .iter()
                .map(|i| format!("{}", enabled[*i].weight.max(1)))
                .collect();
            format!(
                "rotate({{{}}}, {{weights = {{{}}}}})",
                names.join(", "),
                weights.join(", ")
            )
        }
    };

    if scheduled.is_empty() {
        let _ = writeln!(s, "pl = {base}");
        return;
    }

    // Dayparting: a switch whose slots are the scheduled playlists' rules
    // and whose default child is the base composition.
    let mut slots: Vec<String> = Vec::new();
    for &i in &scheduled {
        let src = format!("pl{i}");
        let p = enabled[i];
        for sch in &p.schedules {
            let days = if sch.days.trim().is_empty() {
                String::new()
            } else {
                let names: Vec<String> = sch
                    .days
                    .split(',')
                    .map(|d| d.trim().to_string())
                    .filter(|d| !d.is_empty())
                    .map(|d| format!("{d:?}"))
                    .collect();
                format!("days = {{{}}}, ", names.join(", "))
            };
            slots.push(format!(
                "{{when = {{{days}from = {:?}, to = {:?}}}, src = {src}}}",
                sch.start_time, sch.end_time
            ));
        }
    }
    slots.push(format!("{{src = {base}}}"));
    let _ = writeln!(s, "pl = switch({{{}}})", slots.join(", "));
}

/// Prefix a file path with its `annotate:` fade/cue overrides, if any.
/// Quoted values match the engine's `parse_annotate` expectations.
fn annotate_path(
    path: &str,
    fade_in: Option<f64>,
    fade_out: Option<f64>,
    cue_in: Option<f64>,
    cue_out: Option<f64>,
) -> String {
    let mut parts: Vec<String> = Vec::new();
    if let Some(v) = cue_in {
        parts.push(format!("liq_cue_in=\"{}\"", fmt_f64(v)));
    }
    if let Some(v) = cue_out {
        parts.push(format!("liq_cue_out=\"{}\"", fmt_f64(v)));
    }
    if let Some(v) = fade_in {
        parts.push(format!("liq_fade_in=\"{}\"", fmt_f64(v)));
    }
    if let Some(v) = fade_out {
        parts.push(format!("liq_fade_out=\"{}\"", fmt_f64(v)));
    }
    if parts.is_empty() {
        format!("{path:?}")
    } else {
        // The annotate prefix and path are one Lua string value; `:?`
        // quotes/escapes the whole thing so the value carries the prefix
        // plus the raw path (no stray quotes around the URI).
        format!("{:?}", format!("annotate:{}:{path}", parts.join(",")))
    }
}

/// Render a float the way Lua accepts it (never a bare integer like `3`,
/// always `3.0`, and never a trailing dot like `3.`).
fn fmt_f64(v: f64) -> String {
    let mut s = format!("{v}");
    if !s.contains(['.', 'e']) {
        s.push_str(".0");
    } else if !s.contains('e') {
        while s.ends_with('0') {
            s.pop();
        }
        if s.ends_with('.') {
            s.push('0');
        }
    }
    s
}

/// Validate a rendered script with `crabsoup --check`. The binary path
/// comes from `CRABSOUP_BIN` (default `crabsoup`).
pub fn validate(script: &str, bin: &Path) -> anyhow::Result<String> {
    let dir = std::env::temp_dir().join(format!("crabcast-check-{}", uuid::Uuid::new_v4()));
    std::fs::create_dir_all(&dir)?;
    let path = dir.join("crabsoup.lua");
    std::fs::write(&path, script)?;

    let output = Command::new(bin)
        .arg("--check")
        .arg("-c")
        .arg(&path)
        .output()?;
    let stdout = String::from_utf8_lossy(&output.stdout).into_owned();
    let stderr = String::from_utf8_lossy(&output.stderr).into_owned();

    let _ = std::fs::remove_dir_all(&dir);

    if !output.status.success() {
        anyhow::bail!(
            "crabsoup --check failed (exit {:?}): {}\n{}",
            output.status.code(),
            stdout,
            stderr
        );
    }
    Ok(stdout)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::db::playlists::{PlaylistSchedule, PlaylistSource};

    fn station() -> Station {
        Station {
            id: "s1".into(),
            name: "Test Radio".into(),
            description: "A test station".into(),
            created_at: "2026-01-01T00:00:00.000Z".into(),
            sample_rate: 44100,
            channels: 2,
            frames_per_buffer: 4096,
            crossfade_seconds: 3.0,
            fade_curve: 1.0,
            duck_seconds: 1.5,
            playlist_dir: "/media/test".into(),
            jingles_dir: "/media/jingles".into(),
            harbor_port: 8005,
            harbor_mount: "/live".into(),
            harbor_password: "dj".into(),
            control_port: 1234,
            control_http_port: 9234,
            icecast_host: "localhost".into(),
            icecast_port: 8000,
            icecast_mount: "/radio".into(),
            icecast_format: "mp3".into(),
            icecast_bitrate: 128000,
            icecast_source_user: "source".into(),
            icecast_source_password: "hackme".into(),
            website: String::new(),
            facebook: String::new(),
            twitter: String::new(),
            instagram: String::new(),
        }
    }

    fn source(kind: &str, files: &[&str]) -> PlaylistSource {
        PlaylistSource {
            kind: kind.into(),
            shuffle: false,
            weight: 1,
            files: files
                .iter()
                .map(|f| (f.to_string(), None, None, None, None))
                .collect(),
            schedules: vec![],
        }
    }

    #[test]
    fn render_contains_all_key_sections() {
        let s = render(
            &station(),
            "http://localhost:8080/api/webhooks/track",
            "http://localhost:8080/api/webhooks/blank",
            &[],
            &[],
        );
        for needle in [
            "set(\"sample_rate\", 44100)",
            "set(\"crossfade_seconds\", 3.0)",
            "playlist({directory = \"/media/test\"",
            "jingles({directory = \"/media/jingles\"})",
            "input.harbor({host = \"0.0.0.0\", port = 8005",
            "server.telnet({host = \"127.0.0.1\", port = 1234, http_port = 9234, banner = false})",
            "output.icecast({host = \"localhost\", port = 8000, mount = \"/radio\"",
            "format = \"mp3\"",
            "http_post(\"http://localhost:8080/api/webhooks/track?station=s1\", m)",
            "rq = request.queue()",
            "on_metadata(air, function(m) http_post(",
            "fallback({j, live, rq, pl})",
        ] {
            assert!(s.contains(needle), "missing {needle:?} in:\n{s}");
        }
    }

    #[test]
    fn dead_air_guard_wraps_the_output_chain() {
        let s = render(
            &station(),
            "http://localhost:8080/api/webhooks/track",
            "http://localhost:8080/api/webhooks/blank",
            &[],
            &[],
        );
        assert!(
            s.contains(
                "air = blank.detect(fallback({j, live, rq, pl}), {threshold = -40, duration = 5, exhaust_while_blank = false, on_blank = function() http_post(\"http://localhost:8080/api/webhooks/blank?station=s1\", {}) end})"
            ),
            "{s}"
        );
        assert!(s.contains("output.icecast({host = \"localhost\""), "{s}");
        assert!(
            s.contains("on_metadata(air, function(m) http_post("),
            "on_metadata must sit above blank.detect: {s}"
        );
    }

    #[test]
    fn empty_jingles_dir_omits_the_jingle_source() {
        let mut st = station();
        st.jingles_dir = String::new();
        let s = render(&st, "", "", &[], &[]);
        assert!(s.contains("fallback({live, rq, pl})"), "{s}");
        assert!(!s.contains("j = jingles("), "{s}");
    }

    #[test]
    fn streamer_passwords_are_rendered_as_harbor_extras() {
        let s = render(
            &station(),
            "",
            "",
            &[],
            &["sarah-secret".to_string(), "mj-pw".to_string()],
        );
        assert!(
            s.contains(
                "live = input.harbor({host = \"0.0.0.0\", port = 8005, mount = \"/live\", password = \"dj\", extra_passwords = {\"sarah-secret\", \"mj-pw\"}})"
            ),
            "{s}"
        );
        // No streamers → no extra_passwords key at all.
        let plain = render(&station(), "", "", &[], &[]);
        assert!(!plain.contains("extra_passwords"), "{plain}");
    }

    #[test]
    fn empty_playlists_fall_back_to_directory() {
        let s = render_playlist_sources_string(&[]);
        assert!(
            s.contains("pl = playlist({directory = \"/media/test\""),
            "{s}"
        );
    }

    #[test]
    fn single_playlist_renders_files_source() {
        let pl = vec![source("standard", &["/media/a.mp3", "/media/b.mp3"])];
        let s = render_playlist_sources_string(&pl);
        assert!(
            s.contains("pl0 = playlist({files = {\"/media/a.mp3\", \"/media/b.mp3\"}"),
            "{s}"
        );
        assert!(s.contains("shuffle = false, loop = true"), "{s}");
        assert!(s.contains("pl = pl0"), "{s}");
    }

    #[test]
    fn annotate_overrides_are_embedded() {
        let pl = vec![PlaylistSource {
            kind: "standard".into(),
            shuffle: true,
            weight: 1,
            files: vec![(
                "/media/a.mp3".into(),
                Some(2.0),
                Some(3.0),
                Some(0.5),
                Some(180.0),
            )],
            schedules: vec![],
        }];
        let s = render_playlist_sources_string(&pl);
        // The annotate prefix is one Lua string literal, so the quotes are
        // escaped in the emitted source; crabsoup unescapes on parse.
        assert!(
            s.contains(
                "annotate:liq_cue_in=\\\"0.5\\\",liq_cue_out=\\\"180.0\\\",liq_fade_in=\\\"2.0\\\",liq_fade_out=\\\"3.0\\\":/media/a.mp3"
            ),
            "{s}"
        );
        assert!(s.contains("shuffle = true"), "{s}");
    }

    #[test]
    fn multiple_playlists_rotate_with_weights() {
        let pl = vec![
            source("standard", &["/media/a.mp3"]),
            source("looping", &["/media/b.mp3"]),
        ];
        let s = render_playlist_sources_string(&pl);
        assert!(s.contains("rotate({pl0, pl1}, {weights = {1, 1}})"), "{s}");
        assert!(s.contains("pl = rotate({pl0, pl1}"), "{s}");
    }

    #[test]
    fn scheduled_playlist_renders_switch_with_default() {
        let mut p = source("scheduled", &["/media/morning.mp3"]);
        p.schedules = vec![PlaylistSchedule {
            id: "sch1".into(),
            days: "mon,tue".into(),
            start_time: "09:00".into(),
            end_time: "17:00".into(),
        }];
        let s = render_playlist_sources_string(&[p]);
        assert!(
            s.contains(
                "{when = {days = {\"mon\", \"tue\"}, from = \"09:00\", to = \"17:00\"}, src = pl0}"
            ),
            "{s}"
        );
        // A scheduled-only station still gets an on-air default.
        assert!(s.contains("{src = mksafe(blank())}"), "{s}");
        assert!(s.contains("pl = switch({"), "{s}");
    }

    fn render_playlist_sources_string(playlists: &[PlaylistSource]) -> String {
        let mut s = String::new();
        render_playlist_sources(&mut s, playlists, "/media/test");
        s
    }

    #[test]
    fn fmt_f64_renders_lua_safe_floats() {
        assert_eq!(fmt_f64(3.0), "3.0");
        assert_eq!(fmt_f64(1.5), "1.5");
        assert_eq!(fmt_f64(0.0), "0.0");
    }

    #[test]
    fn validate_rejects_broken_scripts() {
        let err = validate("this is not lua", Path::new("crabsoup")).unwrap_err();
        assert!(err.to_string().contains("failed") || err.to_string().contains("No such file"));
    }

    #[test]
    fn validate_accepts_a_minimal_valid_script_when_binary_exists() {
        // Skip unless a crabsoup binary is available.
        let Ok(bin) = std::env::var("CRABSOUP_BIN") else {
            return;
        };
        let script = r#"
set("sample_rate", 44100)
set("channels", 2)
set("frames_per_buffer", 4096)
output.preview(sine({freq = 440, duration = 1}))
"#;
        let out = validate(script, Path::new(&bin)).unwrap();
        assert!(out.contains("sample_rate") || out.contains("output"));
    }

    #[test]
    fn full_rendered_script_passes_check_when_binary_exists() {
        // Skip unless a crabsoup binary is available. Guards the exact
        // generated shape (incl. the blank.detect dead-air wrapper) against
        // engine syntax drift. The engine refuses empty playlist/jingles
        // dirs at --check, so the station points at a temp dir with one
        // (garbage) audio file — only existence is checked.
        let Ok(bin) = std::env::var("CRABSOUP_BIN") else {
            return;
        };
        let dir = std::env::temp_dir().join(format!("crabcast-check-{}", uuid::Uuid::new_v4()));
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("a.mp3"), b"not real audio but the file exists").unwrap();

        let mut st = station();
        let dir_str = dir.to_str().unwrap().to_string();
        st.playlist_dir = dir_str.clone();
        st.jingles_dir = dir_str.clone();
        let file = dir.join("a.mp3");
        let playlists = vec![source("standard", &[file.to_str().unwrap()])];

        let s = render(
            &st,
            "http://localhost:8080/api/webhooks/track",
            "http://localhost:8080/api/webhooks/blank",
            &playlists,
            &[],
        );
        let out = validate(&s, Path::new(&bin)).unwrap();
        assert!(
            out.contains("sample_rate") || out.contains("output"),
            "unexpected check output: {out}"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }
}
