//! Station model → `crabsoup.lua` generator.
//!
//! The generated script mirrors the engine's example script
//! (`../crabsoup/crabsoup.lua.example`): the PCM bus is pinned with `set()`,
//! sources (playlist, jingles, harbor) are wired into a `fallback`, and the
//! result is broadcast via `output.icecast`. Every generated script must
//! pass `crabsoup --check` before the supervisor applies it (see
//! [`validate`]).

use std::fmt::Write;
use std::path::Path;
use std::process::Command;

use crate::db::stations::Station;

/// Render the station's `crabsoup.lua`.
///
/// No secrets: the harbor/icecast passwords come from the station config,
/// not from env, so a rendered script is self-contained — but `--check`
/// runs against the file, and the file lives under the station's config
/// dir, not in the repo.
///
/// `webhook_url` is the backend's track webhook (the engine's `http_post`
/// carries no headers, so the station id rides in the query string).
pub fn render(station: &Station, webhook_url: &str) -> String {
    let mut s = String::new();
    let _ = writeln!(
        s,
        "-- Generated by crabcast for station {:?}. Do not edit; the server regenerates this.",
        station.id
    );
    let _ = writeln!(s);
    let _ = writeln!(s, "set(\"sample_rate\", {})", station.sample_rate);
    let _ = writeln!(s, "set(\"channels\", {})", station.channels);
    let _ = writeln!(
        s,
        "set(\"frames_per_buffer\", {})",
        station.frames_per_buffer
    );
    let _ = writeln!(s);
    let _ = writeln!(
        s,
        "set(\"crossfade_seconds\", {})",
        fmt_f64(station.crossfade_seconds)
    );
    let _ = writeln!(s, "set(\"fade_curve\", {})", fmt_f64(station.fade_curve));
    let _ = writeln!(
        s,
        "set(\"duck_seconds\", {})",
        fmt_f64(station.duck_seconds)
    );
    let _ = writeln!(s);
    let _ = writeln!(
        s,
        "pl = playlist({{directory = {:?}, shuffle = false, loop = true}})",
        station.playlist_dir
    );
    let _ = writeln!(s);
    if station.jingles_dir.is_empty() {
        let _ = writeln!(s, "j = jingles({{}})");
    } else {
        let _ = writeln!(s, "j = jingles({{directory = {:?}}})", station.jingles_dir);
    }
    let _ = writeln!(s);
    let _ = writeln!(
        s,
        "live = input.harbor({{host = \"0.0.0.0\", port = {}, mount = {:?}, password = {:?}}})",
        station.harbor_port, station.harbor_mount, station.harbor_password
    );
    let _ = writeln!(s);
    let _ = writeln!(
        s,
        "server.telnet({{host = \"127.0.0.1\", port = {}, http_port = {}, banner = false}})",
        station.control_port, station.control_http_port
    );
    let _ = writeln!(s);
    let _ = writeln!(
        s,
        "output.icecast({{host = {:?}, port = {}, mount = {:?}, format = {:?}, bitrate = {}, source_user = {:?}, source_password = {:?}, name = {:?}, description = {:?}, genre = \"Various\", reconnect = 5}}, on_metadata(fallback({{j, live, pl}}), function(m) http_post({:?}, m) end))",
        station.icecast_host,
        station.icecast_port,
        station.icecast_mount,
        station.icecast_format,
        station.icecast_bitrate,
        station.icecast_source_user,
        station.icecast_source_password,
        station.name,
        station.description,
        format!("{webhook_url}?station={}", station.id),
    );
    let _ = writeln!(s);
    s
}

/// Render a float the way Lua accepts it (never a bare integer like `3`,
/// always `3.0`, and never a trailing dot like `3.`).
fn fmt_f64(v: f64) -> String {
    let mut s = format!("{v}");
    if !s.contains(['.', 'e']) {
        s.push_str(".0");
    } else if !s.contains('e') {
        while s.ends_with('0') {
            s.pop();
        }
        if s.ends_with('.') {
            s.push('0');
        }
    }
    s
}

/// Validate a rendered script with `crabsoup --check`. The binary path
/// comes from `CRABSOUP_BIN` (default `crabsoup`).
pub fn validate(script: &str, bin: &Path) -> anyhow::Result<String> {
    let dir = std::env::temp_dir().join(format!("crabcast-check-{}", uuid::Uuid::new_v4()));
    std::fs::create_dir_all(&dir)?;
    let path = dir.join("crabsoup.lua");
    std::fs::write(&path, script)?;

    let output = Command::new(bin)
        .arg("--check")
        .arg("-c")
        .arg(&path)
        .output()?;
    let stdout = String::from_utf8_lossy(&output.stdout).into_owned();
    let stderr = String::from_utf8_lossy(&output.stderr).into_owned();

    let _ = std::fs::remove_dir_all(&dir);

    if !output.status.success() {
        anyhow::bail!(
            "crabsoup --check failed (exit {:?}): {}\n{}",
            output.status.code(),
            stdout,
            stderr
        );
    }
    Ok(stdout)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn station() -> Station {
        Station {
            id: "s1".into(),
            name: "Test Radio".into(),
            description: "A test station".into(),
            created_at: "2026-01-01T00:00:00.000Z".into(),
            sample_rate: 44100,
            channels: 2,
            frames_per_buffer: 4096,
            crossfade_seconds: 3.0,
            fade_curve: 1.0,
            duck_seconds: 1.5,
            playlist_dir: "/media/test".into(),
            jingles_dir: "/media/jingles".into(),
            harbor_port: 8005,
            harbor_mount: "/live".into(),
            harbor_password: "dj".into(),
            control_port: 1234,
            control_http_port: 9234,
            icecast_host: "localhost".into(),
            icecast_port: 8000,
            icecast_mount: "/radio".into(),
            icecast_format: "mp3".into(),
            icecast_bitrate: 128000,
            icecast_source_user: "source".into(),
            icecast_source_password: "hackme".into(),
        }
    }

    #[test]
    fn render_contains_all_key_sections() {
        let s = render(&station(), "http://localhost:8080/api/webhooks/track");
        for needle in [
            "set(\"sample_rate\", 44100)",
            "set(\"crossfade_seconds\", 3.0)",
            "playlist({directory = \"/media/test\"",
            "jingles({directory = \"/media/jingles\"})",
            "input.harbor({host = \"0.0.0.0\", port = 8005",
            "server.telnet({host = \"127.0.0.1\", port = 1234, http_port = 9234, banner = false})",
            "output.icecast({host = \"localhost\", port = 8000, mount = \"/radio\"",
            "format = \"mp3\"",
            "http_post(\"http://localhost:8080/api/webhooks/track?station=s1\", m)",
            "on_metadata(fallback({j, live, pl}), function(m) http_post(",
            "fallback({j, live, pl})",
        ] {
            assert!(s.contains(needle), "missing {needle:?} in:\n{s}");
        }
    }

    #[test]
    fn empty_jingles_dir_renders_an_empty_jingles_source() {
        let mut st = station();
        st.jingles_dir = String::new();
        let s = render(&st, "");
        assert!(s.contains("j = jingles({})"), "{s}");
    }

    #[test]
    fn fmt_f64_renders_lua_safe_floats() {
        assert_eq!(fmt_f64(3.0), "3.0");
        assert_eq!(fmt_f64(1.5), "1.5");
        assert_eq!(fmt_f64(0.0), "0.0");
    }

    #[test]
    fn validate_rejects_broken_scripts() {
        let err = validate("this is not lua", Path::new("crabsoup")).unwrap_err();
        assert!(err.to_string().contains("failed") || err.to_string().contains("No such file"));
    }

    #[test]
    fn validate_accepts_a_minimal_valid_script_when_binary_exists() {
        // Skip unless a crabsoup binary is available.
        let Ok(bin) = std::env::var("CRABSOUP_BIN") else {
            return;
        };
        let script = r#"
set("sample_rate", 44100)
set("channels", 2)
set("frames_per_buffer", 4096)
output.preview(sine({freq = 440, duration = 1}))
"#;
        let out = validate(script, Path::new(&bin)).unwrap();
        assert!(out.contains("sample_rate") || out.contains("output"));
    }
}
